# Generated by Django 4.2.3 on 2023-07-24 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_comentario_articulo_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='comentario',
            name='articulo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='get_comentarios', to='blog.articulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='get_comentarios', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
