# Generated by Django 4.2.3 on 2023-07-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_articulo_comentarios_comentario_articulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(verbose_name='Comentario'),
        ),
    ]
